import type { BookingDocPlaceholders } from "@/lib/bookingOfficialTypes";
import { PRICING_TIER_TEXT_DE } from "@/lib/coursePricing";

/** 4 sayfa × satır listesi — jsPDF ve Vorlage üstü çizim ortak kullanır */
export function getOfficialBookingLines(m: BookingDocPlaceholders): string[][] {
  const p1: string[] = [
    "Campus German Sprachschule,",
    "Buergermeister Smidt Str. 80, 28195 Bremen",
    "info@campusgerman.com / 0 421 4851 7985",
    "",
    `An ${m.first_name} ${m.last_name}    Datum: ${m.doc_date}`,
    m.address_line,
    `${m.postal_code} ${m.adress_city}`,
    m.adress_country,
    "",
    "Anmeldebestaetigung fuer einen Deutsch Intensivkurs",
    "",
    "Sehr geehrte Damen und Herren,",
    "Hiermit bestaetigen wir, dass die unten genannte Person zu einem Deutsch Intensivkurs in unserer Sprachschule angemeldet ist.",
    "",
    "Teilnehmende Person:",
    `Vollstaendigen Name    ${m.first_name} ${m.last_name}`,
    `Geburtsdatum und -ort: ${m.birth_date} - ${m.birth_place}`,
    `Staatsangehoerigkeit:    ${m.nationality}`,
    "",
    "Kursdetails:",
    `Kursstufe:    ${m.course_level}`,
    `Kursbeginn und -ende    ${m.course_start} - ${m.course_end} / ins. ${m.course_total} Woche`,
    `Kursumfang:    ${m.weekly_hours} Ue/W - ${m.course_mode}`,
    "",
    "Der Kurs dient dem Erwerb und der Weiterentwicklung der deutschen Sprachkenntnisse und kann - je nach individuellem Ziel - sowohl der Vorbereitung auf anerkannte Sprachpruefungen (z.B. telc, TestDaF, DSH) als auch einem anschliessenden Studium in Deutschland dienen.",
    "Es handelt sich um einen Vollzeit-Intensivkurs im Praesenzformat mit einem Umfang von mindestens 20 Unterrichtsstunden pro Woche.",
    "",
    "Diese Bestaetigung gilt als offizieller Nachweis der Kursanmeldung und kann im Rahmen von Visums- und Aufenthaltsverfahren bei den zustaendigen Behoerden vorgelegt werden.",
    "",
    "Mit freundlichen Gruessen",
    "Ihsan S. Akman - Der Geschaeftsfuehrer",
    "Campus German Sprachschule GmbH",
  ];

  const p2: string[] = [
    "Campus German Sprachschule,",
    "Buergermeister Smidt Str. 80, 28195 Bremen",
    `An ${m.first_name} ${m.last_name}    Datum: ${m.doc_date}`,
    m.address_line,
    `${m.postal_code} ${m.adress_city}`,
    m.adress_country,
    "",
    "Zahlungsbestaetigung fuer einen Deutsch Intensivkurs",
    "",
    "Sehr geehrte Damen und Herren,",
    "Hiermit bestaetigen wir, dass die unten genannte Person zu einem Deutsch Intensivkurs in unserer Sprachschule angemeldet ist und entsprechende Zahlungen geleistet hat.",
    "",
    `Vollstaendigen Name    ${m.first_name} ${m.last_name}`,
    `Geburtsdatum und -ort: ${m.birth_date} - ${m.birth_place}`,
    `Staatsangehoerigkeit:    ${m.nationality}`,
    "",
    `Kursstufe und Umfang    ${m.course_level} / ins. ${m.course_total} Woche - ${m.course_mode}`,
    "",
    "Zahlungsdetail:",
    `Gesamtbetrag:    ${m.grand_total} EUR`,
    `Bereits gezahlt:    ${m.amount_paid} EUR`,
    `Offener Restbetrag:    ${m.amount_due} EUR`,
    "",
    "Mit freundlichen Gruessen",
    "Ihsan S. Akman - Der Geschaeftsfuehrer",
    "Campus German Sprachschule GmbH",
  ];

  const p3: string[] = [
    "Campus German Sprachschule,",
    `An ${m.first_name} ${m.last_name}`,
    `${m.city} ${m.country}`,
    `Datum: ${m.doc_date}`,
    "",
    "Bescheinigung zur Vorlage bei der Visumsbeantragung",
    "",
    "Persoenliche Angaben:",
    `Vollstaendigen Name    ${m.first_name} ${m.last_name}`,
    `Passnummer:    ${m.passport_no}`,
    `Derzeitiger Wohnort:    ${m.city}, ${m.country}`,
    "",
    `Kursstufe:    ${m.course_level}`,
    `Kursbeginn und -ende    ${m.course_start} - ${m.course_end} / ins. ${m.course_total} Woche`,
    `Kursumfang:    ${m.weekly_hours} Ue/W - ${m.course_mode}`,
    "",
    "Diese Bescheinigung wird zur Unterstuetzung des Visumantrags ausgestellt.",
    "",
    "Mit freundlichen Gruessen",
    "Ihsan S. Akman - Der Geschaeftsfuehrer",
  ];

  const p4: string[] = [
    "Campus German Sprachschule,",
    `An ${m.first_name} ${m.last_name}`,
    `${m.city} ${m.country}`,
    `Datum: ${m.doc_date}`,
    `Angebotsnummer: ${m.offer_no}`,
    "",
    "Angebot fuer Deutsch Intensivkurs",
    "",
    "Kurse & Preise:",
    `Kursstufe:    ${m.course_level}    Wochenpreis (Staffel):    ${m.week_price} EUR`,
    `Ins. Kurswoche ${m.course_total} Woche    Gesamtpreis: ${m.course_price} EUR`,
    `Kursumfang:    ${m.weekly_hours} Ue/W - ${m.UArt}    Zahlungsdetails:    ${m.Zahlungsart}`,
    "",
    `Visum Einladung (50 EUR)    ${m.visa_inv}    BRE Onboarding (100 EUR)    ${m.bre_onb}`,
    `Unterkunftsvermittlung (70 EUR) ${m.unterkunft}    Kursmaterial (30 EUR je 4 Woche) ${m.kurs_mat}`,
    "",
    ...PRICING_TIER_TEXT_DE,
    "",
    `Referenz / Angebotsnr.: ${m.offer_no_}`,
    `Zahlungsbetrag ${m.payment_amount} EUR    Total Betrag: ${m.grand_total} EUR`,
    "",
    "mit Freundlichen Gruessen",
    "Ihsan S. Akman - Der Geschaeftsfuehrer",
  ];

  return [p1, p2, p3, p4];
}
